image: nvcr.io/nvidia/pytorch:21.10-py3
port: 8501
command:
  - /bin/sh
  - '-c'
  - |
    echo ls /opt/models/
    ls /opt/models/
    cp -r /opt/models/* opt/repos/repo/
    echo ls /opt/repos/repo
    ls /opt/repos/repo
    cd /opt/repos/repo
    pip install -r requirements.txt
    streamlit run app.py
models:
  - id: mo8o6kb9j1kn79
    path: /opt/models
repositories:
  dataset: ds698527wz6sque
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/joshua-paperspace/BlendGAN
      name: repo
      ref: main
resources:
  replicas: 1
  instanceType: C4
