jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: https://github.com/joshua-paperspace/BlendGAN
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  GenerateImages:
    inputs:
        repo: CloneRepo.outputs.repo
        pretrainedModels: 
            type: dataset
            with:
                ref: dslaw0wi7htu6t7
        styleImage:
            type: dataset
            with:
                ref: ds2g1qcqgo5krm8
        inputImages:
            type: dataset
            with:
                ref: dszwqn13xpdpm16:64qd0ku
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: >-

        echo 3

        echo ls /inputs

        ls /inputs/

        echo ls /inputs/styleImage

        ls /inputs/styleImage/

        echo ls /inputs/inputImages

        ls /inputs/inputImages/

        echo ls /inputs/pretrainedModels

        ls /inputs/pretrainedModels/

        cd /inputs/repo/

        mkdir ./pretrained_models

        cp /inputs/pretrainedModels/* ./pretrained_models/

        mkdir ./results

        mkdir ./results/generatedImages

        python style_transfer_folder.py --size 1024 --ckpt ./pretrained_models/blendgan.pt --psp_encoder_ckpt ./pretrained_models/psp_encoder.pt --style_img_path /inputs/styleImage/ --input_img_path /inputs/inputImages --outdir ./results/generatedImages

        # python sleep.py

        echo ls ./results

        ls ./results

        echo ls ./results/generatedImages

        ls ./results/generatedImages

        mv ./results/generatedImages/* /outputs/generatedImages/

    needs:
      - CloneRepo
    outputs:
        generatedImages:
            type: dataset
            with:
                ref: ds869um6ka0olpn
    resources:
      instance-type: P4000
