jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: https://github.com/joshua-paperspace/BlendGAN
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  GenerateImages:
    inputs:
        repo: CloneRepo.outputs.repo
        models: 
            type: dataset
            with:
                ref: ds2e0vhp7l25cbl
        styleImage:
            type: dataset
            with:
                ref: dsg88ksz686ox7k
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: >-
        cd /inputs/repo/

        echo ls

        ls

        cp /inputs/models/pretrained_models/* ./pretrained_models/

        python generate_image.py --size 1024 --pics 1 --ckpt ./pretrained_models/blendgan.pt --style_img /inputs/styleImage/bird.png --outdir results/temp_results

        cp results/temp_results /ouputs/
    needs:
      - CloneRepo
    outputs:
        generatedImages:
            type: dataset
            with:
                ref: dsjckwctvtk0cgi
    resources:
      instance-type: A6000
