jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: https://github.com/joshua-paperspace/BlendGAN
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  GenerateImages:
    inputs:
        repo: CloneRepo.outputs.repo
        models: 
            type: dataset
            with:
                ref: dsvvvrd9msdm4eo
        styleImage:
            type: dataset
            with:
                ref: ds2g1qcqgo5krm8
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: >-
        cd /inputs/repo/

        echo ls

        ls

        cp /inputs/pretrained_models/* ./pretrained_models/

        python generate_image.py --size 1024 --pics 1 --ckpt ./pretrained_models/blendgan.pt --style_img /inputs/styleImage/bird.png --outdir ./results/generatedImages

        echo ls ./results/generatedImages

        ls ./results/generatedImages

        mkdir /outputs/generatedImages

        mv ./results/generatedImages/* /outputs/generatedImages/

        echo ls /outputs/

        ls /outputs/

        echo ls /outputs/generatedImages/

        ls /outputs/generatedImages/
    needs:
      - CloneRepo
    outputs:
        generatedImages:
            type: dataset
            with:
                ref: ds869um6ka0olpn
    resources:
      instance-type: P5000
